spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
#  config-location: classpath:mybatis/generatorConfig.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
